Translate 3D volumetric rendering with NeRF
KerasKorea/KEKOxTutorial pull request #205
Opened 2022-10-16 15:26 UTC by parkjh688

3D volumetric rendering with NeRF 번역 했습니다

2023-09-13 05:37 UTC, MijeongJeon commented on 204_3D volumetric rendering with NeRF.md
> +> 이 튜토리얼은 3D 볼륨 렌더링하는 모델인 NeRF를 구현 코드 및 NeRF를 이해하기 위한 배경지식으로 구성되어 있습니다.
> 이 튜토리얼은 ...모델인 NeRF를 구현하는 코드 및....

2023-09-13 05:47 UTC, MijeongJeon requested changes
우아 NeRF 최고! 이걸로 가을이 3D 만들어주세요~
ㅎㅎ 넘 리뷰가 늦어 죄송했습니다. 멋진 컨텐츠 번역해주셔서 정말 감사해요 👍🏻👍🏻
제 코멘트 체크해주시면 바로 머지 고고!

2023-09-13 05:47 UTC, MijeongJeon commented on 204_3D volumetric rendering with NeRF.md
> +## NeRF로 해보는 3D volumetric rendering
🤗 일년을 기다린 리뷰! 지금 시작합니다~ 두둥

2023-09-13 05:47 UTC, MijeongJeon commented on 204_3D volumetric rendering with NeRF.md
> +위 설명에 대해 당신을 직관적으로 돕기 위해, 이 질문으로 시작해봅시다: 이미지에서 픽셀의 위치를 뉴럴넷에 주고 그 위치의 색을 예측하도록 요청하는 것이 가능할까요?
아니 대체 뉴럴넷은 얼마나 똑똑한거에요? 저는 못하겠는걸요? 🤔

2023-09-13 05:47 UTC, MijeongJeon commented on 204_3D volumetric rendering with NeRF.md
> +        near: The near bound of the volumetric scene.
얘네도 번역해주세요오

2023-09-13 05:47 UTC, MijeongJeon commented on 204_3D volumetric rendering with NeRF.md
> +        # Inject uniform noise into sample space to make the sampling
여기두 한글화해주세요 ㅎㅎㅎ

2023-09-13 05:47 UTC, MijeongJeon commented on 204_3D volumetric rendering with NeRF.md
> +이 모델은 ReLU를 사용하는 하는 다층 퍼셉트론(MLP)입니다.
사용하는 하는 하는 하는 하는

2023-09-14 05:09 UTC, parkjh688 commented on 204_3D volumetric rendering with NeRF.md
> +이 모델은 ReLU를 사용하는 하는 다층 퍼셉트론(MLP)입니다.
수정했습했습했습니다~

2023-09-14 05:09 UTC, parkjh688 commented on 204_3D volumetric rendering with NeRF.md
> +        # Inject uniform noise into sample space to make the sampling
했습니다~

2023-09-14 05:14 UTC, parkjh688 commented on 204_3D volumetric rendering with NeRF.md
> +        near: The near bound of the volumetric scene.
네엥~

2023-09-14 05:18 UTC, parkjh688 commented
> 우아 NeRF 최고! 이걸로 가을이 3D 만들어주세요~ ㅎㅎ 넘 리뷰가 늦어 죄송했습니다. 멋진 컨텐츠 번역해주셔서 정말 감사해요 👍🏻👍🏻 제 코멘트 체크해주시면 바로 머지 고

2023-09-14 05:29 UTC, parkjh688 commented on 204_3D volumetric rendering with NeRF.md
> +> 이 튜토리얼은 3D 볼륨 렌더링하는 모델인 NeRF를 구현 코드 및 NeRF를 이해하기 위한 배경지식으로 구성되어 있습니다.
수정했습니다~

2023-09-15 11:51 UTC, MijeongJeon approved these changes

2023-09-15 11:51 UTC, merged